### PR TITLE
Added templates for enums.{h,c}

### PR DESCRIPTION
**Pull request by vovochka404**
It's easier to understand/fix something and much more simple to use without mkenums script.

### CODE REVIEW

**Comment by jjk-jacky** [comment]
So there are two things being done here actually: switching to template
files, and changing the generated code. So this should be separated, at
least in two different commits, e.g. one to switch to templates, then
another one to change the code.

As far as using a template, that's fine. I'm not sure why changing the
code is needed however?

**Comment by vovochka404** [comment]
About code changing:
It was easier to take a common template nether to write it from 0 and "parse" you arguments to glib-mkenums :)
Please, accept this commit as is :)

**Comment by jjk-jacky** [comment]
Well, that's not a very good reason to change code and start using
thread-related APIs though.
If you're looking for models, you can have a look at GDK[1], they
generate similar code using templates.

[1] https://git.gnome.org/browse/gtk+/tree/gdk/gdkenumtypes.c.template

**Comment by vovochka404** [comment]
Ok, rewritten :)

**Comment by vovochka404** [comment]
So? :)

**Comment by jjk-jacky** [comment]
Oh, sorry. Yeah it's good, thank you. I've merged this into next, just
haven't pushed it yet.

**Pull request closed without merging**
